### ISSUE TITLE
Install multiple versions

### ISSUE THREAD

**Issue by kierzniak** [geerlingguy/ansible-role-php-versions#11]
It would be nice to have possibility to install multiple versions of php at same machine. Sury packages gives as such a option.

https://github.com/oerdnj/deb.sury.org/wiki/Managing-Multiple-Versions

**Comment by geerlingguy** [comment]
It would be nice, but it's extremely hard to support across 4 main OSes (and some others that I use this role for as well). I'd recommend using multiple VMs (one per version), or multiple Docker containers (one per version) as it makes a heck of a lot of things less obtuse.

**Comment by Callisto88** [comment]
@kierzniak i have the exact same wish =) deploying multiples versions of PHP would be great. Of course i understand @geerlingguy point of view.
Did you find an alternative way to do so ?

**Comment by kierzniak** [comment]
Not really, I decide to host applications with Docker and manage PHP version from application directly not from OS.

**Comment by Callisto88** [comment]
Thanks for your quick reply @kierzniak 👍 Sure Docker provides great flexibility and i am now considering this option as well. Cheers
