### ISSUE TITLE
Error with PHP5 on Ubuntu 18.04 (php5-compat n/a)

### ISSUE THREAD

**Issue by MMerkens** [geerlingguy/ansible-role-php-versions#18]
Hi,
I tried to install PHP 5.6 on my Ubuntu 18.04 and it failed because php5-compat is not supporting it.
Maybe it could be just copied by the owner for 18.04 or a check for ubuntu version < 18.04 should be added.

`TASK [geerlingguy.php-versions : Add repository for PHP 5 compatibility packages (Ubuntu).] ****************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt.cache.FetchFailedException: E:The repository 'http://ppa.launchpad.net/ondrej/php5-compat/ubuntu bionic Release' does not have a Release file.
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_WQze8a/ansible_module_apt_repository.py\", line 551, in <module>\n    main()\n  File \"/tmp/ansible_WQze8a/ansible_module_apt_repository.py\", line 543, in main\n    cache.update()\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 505, in update\n    raise FetchFailedException(e)\napt.cache.FetchFailedException: E:The repository 'http://ppa.launchpad.net/ondrej/php5-compat/ubuntu bionic Release' does not have a Release file.\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
            to retry, use: --limit @/home/username/install/playbook.retry
`

**Comment by geerlingguy** [comment]
@MMerkens - Good catch; though it seems like Ondrej's repos should support 5.6 on Ubuntu 18.04: https://launchpad.net/~ondrej/+archive/ubuntu/php?field.series_filter=bionic

Will have to take a look. I've only tested 7.2 on Bionic so far.

**Comment by 0xffea** [comment]
The error is from the php5-compat repo (not from ppa:ondrej/php), which has no release for bionic.

**Comment by geerlingguy** [comment]
Testing a fix now.
