### ISSUE TITLE
Using geerlingguy.php-versions prevents overriding geerlingguy.php's php_packages variable

### ISSUE THREAD

**Issue by ctorgalson** [geerlingguy/ansible-role-php-versions#19]
Greetings.

We just found out about and started to test this role alongside your `geerlingguy.php` role (thanks for these!)

Unfortunately, we've found that this role makes it impossible to customize `geerlingguy.php`'s `php_packages` variable. I'm fairly sure this isn't a case of us misunderstanding the use or one or both roles, but I guess that's always a possibility :smile:.

For example, the following variable definition in a playbook works _unless_ the `geerlingguy.php-versions` role is used:

```yaml
    # Replace default var with the same list, with mod-php and minus php7.1-fpm.
    php_packages:
      - "php{{ php_version }}"
      - "php{{ php_version }}-apcu"
      - "php{{ php_version }}-cli"
      - "php{{ php_version }}-common"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-dev"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-imap"
      - "php{{ php_version }}-json"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-mcrypt"
      - "php{{ php_version }}-opcache"
      - "php{{ php_version }}-sqlite3"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-yaml"
      - "libapache2-mod-php{{ php_version }}"
```
I've created a git repo containing a playbook and Vagrantfile to demonstrate both the working and non-working configurations: https://github.com/ctorgalson/php-versions

**Comment by geerlingguy** [comment]
@oxyc and I wrote this role _mostly_ to make it super easy for people to switch between 5.6, 7.0, 7.1, and 7.2 on Drupal VM (https://www.drupalvm.com), and only when used in tandem with `geerlingguy.php`.

That said, if you just want to _add_ packages to the list, the best way is to use the `php_packages_extra` variable in the `geerlingguy.php` role, and add additional packages there.

I admit the use case of this role is slightly narrow in that, if you don't need all the packages this role manages, and can't live with the extra packages being installed, then the best option is to fork the role and customize it to your needs—or as you say, drop using this role and manage the `php_packages` list entirely on your own.

**Comment by ctorgalson** [comment]
> @oxyc and I wrote this role mostly to make it super easy for people to switch between 5.6, 7.0, 7.1, and 7.2 on Drupal VM.

Fair enough. We'd been managing the php versions aspect manually up til now in any case. Thanks for the feedback (and also for the million-and-one roles)!

**Comment by ajardan** [comment]
@ctorgalson you can use a group or host var to override this.
