### ISSUE TITLE
Overwrite of custom defined php packages

### ISSUE THREAD

**Issue by morpheus-87** [geerlingguy/ansible-role-php-versions#30]
At the moment, this role overwrites the php packages that are defined in the playbook. Is there any valuable reason to do that?

**Comment by geerlingguy** [comment]
@morpheus-87 - This role is intended as a helpful way to make it easier to change PHP versions, and nothing more—if you need any more advanced control, I recommend setting the versions manually and setting up the appropriate repo and not using the role, or forking the role to do what you'd like to be able to do more easily.

This role was originally created only for Drupal VM, so the use case is intentionally a bit narrow. It would be excruciatingly difficult to try to take an existing list of php packages (which could be for one of 5 or 6 different platforms/package naming conventions) and transform it appropriately for different PHP versions.

If this role targeted only RHEL/CentOS/Fedora it would be a bit easier, but this role is meant to work across Debian/Ubuntu releases as well, where PHP versions are part of the package names (not that I agree with that design decision, but it is what it is).
