### ISSUE TITLE
Debian 9 multiple php version

### ISSUE THREAD

**Issue by Nurlan199206** [geerlingguy/ansible-role-php-versions#33]
i can install multiple php versions on my Debian 9 with your playbook?

**Comment by niavlysAO** [comment]
as of now, I think it's not possible, but I agree it'd be great.

**Comment by geerlingguy** [comment]
No, currently I don't plan on supporting running multiple PHP versions, as it adds a lot of complexity and I only use this role in situations where I want to be able to choose a specific version or switch versions.
