### ISSUE TITLE
Add variable to toggle removal of older PHP verions

### ISSUE THREAD

**Issue by kindlehl** [geerlingguy/ansible-role-php-versions#40]
My organization finds it very useful to run two versions of PHP-FPM. This role nearly accomplishes this goal, but the purge task in `setup-Debian.yml` stops that from working for us. 

Would you be willing to allow a `when` condition to be added to toggle that task? Maybe call it `php_remove_old_versions`? Not sure how this would work for the RedHat side of things, though.

**Comment by geerlingguy** [comment]
It would definitely cause issues on the RedHat side, so maybe if this were added, it would be a Debian/Ubuntu-only deal.

**Comment by gesof** [comment]
I subscribe to adding a condition to avoid purging. You mentioned about issues with RedHat: it is their issue not an Ubuntu/Debian-only deal. It is more and more common to run multiple PHP versions on one machine.
