### ISSUE TITLE
Support php version switch for existing setups

### ISSUE THREAD

**Issue by mhitza** [geerlingguy/ansible-role-php-versions#49]
I'd like to integrate the necessary steps to support PHP version upgrades for already provisioned systems; without dropping manually in a shell to do the setup.

The error message is helpful enough, that outside some additional checks, should be straightforward.

```
The operation would result in switching of module 'php' stream 'remi-7.3' to stream
'remi-7.4' Error: It is not possible to switch enabled streams of a module. It is
recommended to remove all installed content from the module, and reset the module
using 'dnf module reset <module_name>' command. After you reset the module, you
can install the other stream
```

If there's interest to support this functionality in this role, let me know and I'll work on it.

**Comment by geerlingguy** [comment]
It actually works (I believe) on Debian based systems. If it's a simple enough change to get it working on Red Hat based systems also, I would consider accepting the change.
