### ISSUE TITLE
switching of module 'php' stream '7.2' to stream 'remi-7.4

### ISSUE THREAD

**Issue by MacFlurry** [geerlingguy/ansible-role-php-versions#52]
Hello,

I encounter an issue on CentOS 8 where I wanted to use a 7.4 version of the repo remi.
and I got this error:
```
TASK [galaxy-php-versions : Enable DNF module for CentOS 8+.] ***********************************************************************
fatal: [orc-admin.test]: FAILED! => changed=true
  cmd: |-
    dnf config-manager --set-enabled PowerTools
    dnf module enable -y php:remi-7.4
  delta: '0:00:13.355465'
  end: '2020-09-09 14:34:02.534515'
  msg: non-zero return code
  rc: 1
  start: '2020-09-09 14:33:49.179050'
  stderr: |-
    The operation would result in switching of module 'php' stream '7.2' to stream 'remi-7.4'
    Error: It is not possible to switch enabled streams of a module.
    It is recommended to remove all installed content from the module, and reset the module using 'dnf module reset <module_name>' command. 
  After you reset the module, you can install the other stream.
  stderr_lines: <omitted>
  stdout: |-
    CentOS-8 - PowerTools                           246 kB/s | 1.9 MB     00:07
    Last metadata expiration check: 0:00:04 ago on Wed 09 Sep 2020 02:33:56 PM UTC.
    Dependencies resolved.
  stdout_lines: <omitted>
```

any Idea ? @geerlingguy 

Thanks for your help

**Comment by mhitza** [comment]
The error fixed in my PR is a bit different though, as it makes it possible to switch between `remi-*` streams, you seem to have installed PHP without remi repos at first. And then tried to switch to it.

You can delete all the PHP packages, reset the `php` module, and then switch to remi. That's how the fix works for the PR I made.

**Comment by MacFlurry** [comment]
correct, so could you pls implement my use case also ? If you don't mind 🥰😘

**Comment by geerlingguy** [comment]
Yeah the hard thing is I don't know how to cleanly account for the case where someone installs PHP outside of using remi's repos, then wants to automatically have that uninstalled before installing from remi. I think it is a reasonable assumption for this role to be used on a clean install, or to expect the end user to clean up any old non-automated PHP installations manually beforehand.

**Comment by MacFlurry** [comment]
It would be nice indeed to propose to remove the current version of PHP before installation.
If it's not too complicated to do.
