### ISSUE TITLE
Task adding the Ondrej Sury's apt key tries to download it every time

### ISSUE THREAD

**Issue by luminouw** [geerlingguy/ansible-role-php-versions#54]
Hello here,

I have a question regarding the use of the `apt_key` module when sitting up in a corporate restricted environment.

The documentation of the module specifies that `apt_key` should only try and download the key if it really needs it. On the machines I plan to use this role with restricted connectivity to the outside world, the key is shipped beforehand by our Ansible controllers and added to the hosts.

Since the `key_id` isn't specified in the task, and even though the key actually exists on the system, it tries to download it and fails every time at this stage.

Question(s) :

- Would it be relevant to add Ondrej Sury's key ID to the role / task ? And thus preventing the systematic  download if unnecessary.
- If managing and updating the ID is cumbersome, would adding another condition (eg. `when: ansible_distribution == "Debian" and skip_apt_key_tasks == True`) be an option that you'd consider ?

Reality is the majority of people using this won't ever face this issue, but there are still lots of corporate networks well buried behind a shitload of proxies and security decisions that won't be allowed directly on the internet (I know, not really "cloud" friendly) and most existing roles don't even take into account the possibility of a single proxy :( 

Let me know what you think !

Thanks

**Comment by luminouw** [comment]
Bump :)

**Comment by webarchitect609** [comment]
@geerlingguy , if I get it right, since #59 is merged and closed, this issue can be closed without regret as well :)

**Comment by geerlingguy** [comment]
Yep! Should be fixed now.
