### ISSUE TITLE
Role is not present in the Ansible Galaxy

### ISSUE THREAD

**Issue by piotrkochan** [geerlingguy/ansible-role-php-versions#60]
```
[WARNING]: - geerlingguy.php-versions was NOT installed successfully: - sorry, geerlingguy.php-versions was not found on 
https://galaxy.ansible.com/api/.
```
https://galaxy.ansible.com/search?deprecated=false&keywords=php-versions&order_by=-relevance&page=1

**Comment by romanos-compucorp** [comment]
Looks like it's been renamed to php_versions.
https://galaxy.ansible.com/geerlingguy/php_versions

**Comment by geerlingguy** [comment]
See upstream bug: https://github.com/ansible/galaxy/issues/2622

I was trying to get linting working again, and the role name changed out from under me again :(

**Comment by gotmax23** [comment]
It looks like the role is currently available under `geerlingguy.php-versions` on Galaxy.
