### ISSUE TITLE
ansible-lint still sees errors

### ISSUE THREAD

**Issue by webarchitect609** [geerlingguy/ansible-role-php-versions#62]
@geerlingguy , please, check out PR #61 which [fixes the following errors and warnings](https://github.com/geerlingguy/ansible-role-php-versions/actions/runs/590798222) by ansible-lint:
- error: `internal-error the role 'geerlingguy.repo-remi' was not found in...`
- error: `syntax-check 'src' is not a valid attribute for a Play`
- warning: `[line-length] line too long (173 > 120 characters)`

P.S.: And thanks for applying my PR #55 ; now I will mark my fork as 'deprecated' and return control to 'the mothership' :)

**Comment by geerlingguy** [comment]
For now I'm dropping using `ansible-lint` for my roles, as there are too many little annoyances to keep up with it.
