### ISSUE TITLE
using php_version: '7.4' installs php 8.0

### ISSUE THREAD

**Issue by khallouki** [geerlingguy/ansible-role-php-versions#65]
Hello,

I am trying to install php 7.4 on a new debian 10 server. Whenever I use php_version: '7.4' and php_default_version_debian: '7.4' for the ansible-role-php role it installs the version 8.0.

Am I missing a configuration somewhere?

Thank you in advance.

Greetings,
Khallouki

**Comment by geerlingguy** [comment]
Are you using the `geerlingguy.php-versions` role?

**Comment by khallouki** [comment]
Hello, 

Yes I am using geerlingguy.php-versions and geerlingguy.php. I noticed that php 7.4 is installed however the php packages are for php 8.0 (cli, fpm etc.). This is my configuration: 

`php_version: '7.4'
php_default_version_debian: '7.4'
php_packages:
  - php-cli
  - php-fpm
  - php-soap
  - php-mysql
  - php-mbstring
  - php-xml
  - php-intl
  - php-gd
  - php-imagick
  - php-zip
  - php-curl`

This has been going good for a while until now, the packages are for 8.0. Do I need to use php7.4-cli etc.?

**Comment by khallouki** [comment]
I fixed it by using these values for php_packages:

`php_packages:
  - php7.4-cli
  - php7.4-fpm
  - php7.4-soap
  - php7.4-mysql
  - php7.4-mbstring
  - php7.4-xml
  - php7.4-intl
  - php7.4-gd
  - php7.4-imagick
  - php7.4-zip
  - php7.4-curl`

**Comment by geerlingguy** [comment]
@khallouki - Yeah, if you override `php_packages`, then you should ideally put `{{ php_version }}` where it belongs (e.g. in place of `7.4` to match the functionality in the `php_versions` role.
