### ISSUE TITLE
php8.0-json is part of PHP

### ISSUE THREAD

**Issue by Roboroads** [geerlingguy/ansible-role-php-versions#69]
Since PHP8 php-json is now part of php, so when installing this package gives an error.

```
fatal: [host1]: FAILED! => {"cache_update_time": 1630450023, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'php8.0' 'php8.0-apcu' 'php8.0-cli' 'php8.0-common' 'php8.0-curl' 'php8.0-dev' 'php8.0-fpm' 'php8.0-gd' 'php8.0-imap' 'php8.0-json' 'php8.0-mbstring' 'php8.0-opcache' 'php8.0-sqlite3' 'php8.0-xml' 'php8.0-yaml' -o APT::Install-Recommends=yes' failed: E: Package 'php8.0-json' has no installation candidate\n", "rc": 100, "stderr": "E: Package 'php8.0-json' has no installation candidate\n", "stderr_lines": ["E: Package 'php8.0-json' has no installation candidate"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nPackage php8.0-json is a virtual package provided by:\n  php8.0-phpdbg 8.0.10-1+ubuntu20.04.1+deb.sury.org+1\n  php8.0-fpm 8.0.10-1+ubuntu20.04.1+deb.sury.org+1\n  php8.0-cli 8.0.10-1+ubuntu20.04.1+deb.sury.org+1\n  php8.0-cgi 8.0.10-1+ubuntu20.04.1+deb.sury.org+1\n  libphp8.0-embed 8.0.10-1+ubuntu20.04.1+deb.sury.org+1\n  libapache2-mod-php8.0 8.0.10-1+ubuntu20.04.1+deb.sury.org+1\n\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Package php8.0-json is a virtual package provided by:", "  php8.0-phpdbg 8.0.10-1+ubuntu20.04.1+deb.sury.org+1", "  php8.0-fpm 8.0.10-1+ubuntu20.04.1+deb.sury.org+1", "  php8.0-cli 8.0.10-1+ubuntu20.04.1+deb.sury.org+1", "  php8.0-cgi 8.0.10-1+ubuntu20.04.1+deb.sury.org+1", "  libphp8.0-embed 8.0.10-1+ubuntu20.04.1+deb.sury.org+1", "  libapache2-mod-php8.0 8.0.10-1+ubuntu20.04.1+deb.sury.org+1", ""]}
```

**Comment by geerlingguy** [comment]
This is already done if you're installing PHP 8—or at least it should be... see: https://github.com/geerlingguy/ansible-role-php-versions/blob/7ea6036859ba2a36e2bc148258985b94592851d2/tasks/main.yml#L8-L13

**Comment by Roboroads** [comment]
Fun fact. I had updates the role - in the wrong folder :facepalm: 

Excuse me!

**Comment by Harishm04** [comment]
Hi @Roboroads 

Could you please provide me the details on updating the PHP version to 8 on Drupal VM. Steps I did,

Updated php_version: 8.0 in config.yml file and installed ansible-galaxy install geerlingguy.php-versions and tried to run vagrant reload --provisioning but I am facing the error **php8.0-json is not an installation candidate**. 
I updated the php_version: 8.0 inside ansible/roles/geerlingguy.php_versions/default/main.yml file as well.

Thanks,
Harish M.

**Comment by Roboroads** [comment]
@Harishm04 You might be trying to install php-json in your php_packages variable. Remove that for php 8.

json is now included in PHP, and no extra package like php-json is needed anymore like <=7.4

**Comment by Harishm04** [comment]
Hi @Roboroads 

Thanks for the response. I am actually using Drupal VM (geerlingguy/drupal-vm) with Vagrant & Ansible for local development. I have not included the php8-json package anywhere specifically. 
In the config.yml below are the settings related to PHP,

php_version: "8.0"
php_packages_extra:
  - "php{{ php_version }}-bz2"
  - "php{{ php_version }}-imagick"
  - "imagemagick"
  - "php{{ php_version }}-zip"
php_install_recommends: no
php_memory_limit: "-1"
php_display_errors: "On"
php_display_startup_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/opt/mailhog/mhsendmail"
php_opcache_enable: "1"
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"
php_max_execution_time: "0"

When PHP version is 7.4 it works fine but like you said when we change to 8.0 it tries to fetch php8-json package from the Drupal VM (geerlingguy package) I guess which I am not sure how to exclude that package.

Thanks,
Harish M.
