### ISSUE TITLE
Question: Is it possible to install 2 or more PHP versions at the same time?

### ISSUE THREAD

**Issue by tomasnorre** [geerlingguy/ansible-role-php-versions#74]
Hi.

I'm currently setting up a new Web server, which has multiple projects with multiple requirements, like different PHP versions. 

I would therefore need both php7.4-fpm and php8.0-fpm. I haven't found a way to do this with the Role. Am I missing something? Or not possible with this role?

**Comment by geerlingguy** [comment]
This role is only meant to install/manage one PHP version at a time. The ideal use case is on a server that supports a single version of PHP, or in container installs, where you'd have containers specific to each project.

**Comment by tomasnorre** [comment]
Thanks. I don't have all my things in containers, but get your point. Thanks.
