### ISSUE TITLE
Fault enabling CRB on AlmaLinux 9

### ISSUE THREAD

**Issue by ben-dataraven** [geerlingguy/ansible-role-php-versions#89]
On AlmaLinux9, the dnf module name is **crb** rather than **powertools**

This causes a fault with the **Enable DNF module for CentOS 8+** task

https://wiki.almalinux.org/repos/Extras.html

**Comment by geerlingguy** [comment]
@ben-dataraven - Indeed! I just noticed this on my `munin` role as well: https://github.com/geerlingguy/ansible-role-munin/issues/17

I will update this role to use `crb` and hopefully that works!

**Comment by geerlingguy** [comment]
Fixed in 6.2.0!
