### ISSUE TITLE
PHP 8.3 support?

### ISSUE THREAD

**Issue by chrisdeeming** [geerlingguy/ansible-role-php-versions#90]
Is it possible to add PHP 8.3 @geerlingguy?

Many thanks

**Comment by geerlingguy** [comment]
@chrisdeeming - 8.3 should be possible even if it's not officially set as a default / tested option, but I'll work on making it a more supported/tested release.

**Comment by chrisdeeming** [comment]
Thanks @geerlingguy i did think that but when I ran it earlier it didn't do the actual upgrade from 8.2. Maybe I did something wrong.

**Comment by geerlingguy** [comment]
Ah well - try out the latest code I just pushed (it's not yet in a tagged release) and see if that helps!

**Comment by chrisdeeming** [comment]
I pulled this role from `master` and it now works. Thanks Jeff!

**Comment by geerlingguy** [comment]
Excellent! I've pushed the new tag now that you can confirm it helps!
